# No Title

[Original Post](https://discourse.onlinedegree.iitm.ac.in/t/164277/538)

<p>I am getting this error while running evaluate.py on task A9</p>
<pre data-code-wrap="bash"><code class="lang-bash">HTTP Request: POST https://aiproxy.sanand.workers.dev/openai/v1/embeddings "HTTP/1.1 401 Unauthorized"

ðŸ”´ A9 failed: 'data'
</code></pre>
<p>There were no authentication issues till yesterday.</p>
<p>please guide <a class="mention" href="/u/carlton">@carlton</a> <a class="mention" href="/u/jivraj">@Jivraj</a> <a class="mention" href="/u/saransh_saini">@Saransh_Saini</a></p>